### ISSUE TITLE
Cannot Boot Big Sur Installer

### ISSUE THREAD

**Issue by vaishnavvprabhu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#121]
I am not able to boot Big Sur installer. When I select "Boot from install Big Sur Beta", I only have an apple logo and no progress bar. My laptop hangs.
I even tried using clover but it just hangs after "EXITBS START".

**Comment by xiaoMGitHub** [comment]
3.0.3 version will provide support

**Comment by indowebdeveloper** [comment]
how do we get the 3.0.3 version ? @xiaoMGitHub

**Comment by indowebdeveloper** [comment]
Hello @xiaoMGitHub , is there any latest info on when you gonna release the 3.0.3 version, since its been few days after official release of Big Sur ? 
i saw that if we want to get it now we should join your qq group, but i cant speak nor read chinese,
did you have any international messenger platform ?
